theme = "gruvbox-dark"
icons = "awesome5"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mug}GB/{MTg}GB ({Mup}%)"
format_swap = "{SUg}GB/{STg}GB ({SUp}%)"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "battery"
format = "{percentage}% ({time})"

[[block]]
block = "networkmanager"
ap_format = "{ssid} {strength}%"
device_format = "{icon} {ap}"

[[block]]
block = "time"
format = "%a %d/%m %r"
interval = 1

[[block]]
block = "watson"
show_time = true

[[block]]
block = "sound"
